CREATE TABLE IF NOT EXISTS endpoint_hits
(
    id       INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    app      VARCHAR(255)                         NOT NULL,
    uri      VARCHAR(1000)                        NOT NULL,
    ip       VARCHAR(16)                          NOT NULL,
    received TIMESTAMP                            NOT NULL
);